### ISSUE TITLE
leave_AugAssign crashes

### ISSUE THREAD

**Issue by coderforlife** [teemulehtinen/pyqlc#1]
In `qlcpy/instrument/TransformForInstrumentor.py` the line `BinOp(Name(node.target.id, Load()), node.op, node.value)` crashes since "AttributeError: 'Subscript' object has no attribute 'id'".

**Comment by teemulehtinen** [comment]
Thanks for the report! Based on that, code transformation fails when the code includes: foo[bar] += 1 type of assignment. Surprisingly, any of the code we have run through this did not include such structures. I will set up a test for this case and fix it later today or tomorrow.

**Comment by coderforlife** [comment]
Awesome! I couldn’t figure out quite how to fix it without breaking everything else. I am not too familiar with the AST traversal stuff.

**Comment by teemulehtinen** [comment]
The error is fixed in 1.0.18 at PyPI or the latest commit in the main branch. However, the assignment history of array elements is ignored. I believe they should not be treated identically to "regular variables" as that would likely be confusing.
